<?xml version="1.0" encoding="utf-8"?><Database Name="SimchaFund" Class="ContributorDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=TOMMY\SQLEXPRESS;Initial Catalog=SimchaFund;Integrated Security=True" SettingsObjectName="Simcha_Fund.Data.Properties.Settings" SettingsPropertyName="SimchaFundConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Contributors" Member="Contributors">
    <Type Name="Contributor">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="FirstName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="LastName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="CellNumber" Type="System.String" DbType="VarChar(11) NOT NULL" CanBeNull="false" />
      <Column Name="AlwaysInclude" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Date" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>